packages:
  - packages/*
  - examples/*
onlyBuiltDependencies:
  - simple-git-hooks
catalog:
  "@fisch0920/config": ^1.1.2
  "@fisch0920/eslint-config": ^1.4.0
  "@fisch0920/medium-zoom": ^1.0.7
  "@matejmazur/react-katex": ^3.1.3
  "@notionhq/client": ^2.3.0
  "@total-typescript/ts-reset": ^0.6.1
  "@types/lodash.throttle": ^4.1.6
  "@types/node": ^22.15.30
  "@types/prismjs": ^1.26.5
  "@types/react": ^19.1.6
  "@types/react-dom": ^19.1.6
  "@types/react-modal": ^3.16.3
  bumpp: ^10.1.1
  classnames: ^2.5.1
  clipboard-copy: ^4.0.1
  cross-env: ^7.0.3
  date-fns: ^4.1.0
  del-cli: ^6.0.0
  eslint: ^9.28.0
  format-number: ^3.0.0
  is-url-superb: ^6.1.0
  katex: ^0.16.21
  ky: ^1.8.1
  lodash.throttle: ^4.1.1
  lqip-modern: ^2.1.0
  memoize: ^10.1.0
  next: ^15.3.3
  normalize-url: ^8.0.1
  npm-run-all2: ^8.0.4
  p-map: ^7.0.3
  p-memoize: ^7.1.1
  p-queue: ^8.1.0
  prettier: ^3.5.3
  prismjs: ^1.30.0
  react: ^19.1.0
  react-dom: ^19.1.0
  react-fast-compare: ^3.2.0
  react-hotkeys-hook: ^4.5.1
  react-image: ^4.0.3
  react-lazy-images: ^1.1.0
  react-modal: ^3.16.3
  react-scripts: 5.0.1
  react-tweet-embed: ^2.0.0
  simple-git-hooks: ^2.13.0
  tsup: ^8.5.0
  tsx: ^4.19.4
  turbo: ^2.5.4
  typescript: ^5.8.3
  vitest: ^3.2.2
