packages:
  - packages/*
  - examples/*

catalog:
  '@fisch0920/config': ^1.4.0
  '@fisch0920/eslint-config': ^1.4.0
  '@fisch0920/medium-zoom': ^1.0.7
  '@matejmazur/react-katex': ^3.1.3
  '@notionhq/client': ^2.3.0
  '@total-typescript/ts-reset': ^0.6.1
  '@types/lodash.throttle': ^4.1.6
  '@types/node': ^25.2.3
  '@types/prismjs': ^1.26.5
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@types/react-modal': ^3.16.3
  bumpp: ^10.4.1
  classnames: ^2.5.1
  clipboard-copy: ^4.0.1
  cross-env: ^7.0.3
  date-fns: ^4.1.0
  del-cli: ^7.0.0
  eslint: ^9.35.0
  format-number: ^3.0.0
  is-url-superb: ^6.1.0
  katex: 0.16.21
  ky: ^1.8.1
  lodash.throttle: ^4.1.1
  lqip-modern: ^2.1.0
  memoize: ^10.1.0
  next: ^16.1.6
  normalize-url: ^8.0.1
  npm-run-all2: ^8.0.4
  ofetch: ^1.4.1
  p-map: ^7.0.3
  p-memoize: ^7.1.1
  p-queue: ^8.1.0
  prettier: ^3.8.1
  prismjs: ^1.30.0
  react: ^19.2.4
  react-dom: ^19.2.4
  react-fast-compare: ^3.2.0
  react-hotkeys-hook: ^4.5.1
  react-image: ^4.0.3
  react-intersection-observer: ^9.16.0
  react-modal: ^3.16.3
  react-scripts: 5.0.1
  react-tweet-embed: ^2.0.0
  simple-git-hooks: ^2.13.1
  tsup: ^8.5.1
  tsx: ^4.21.0
  turbo: ^2.8.7
  typescript: ^5.9.3
  unionize: ^3.1.0
  vitest: ^3.2.4

enablePrePostScripts: true

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - simple-git-hooks

packageManagerStrict: false
